apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-postgres
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.11.1
    chart: postgresql
    helm:
      releaseName: example-postgres
      values: |
        # https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
        auth:
          enablePostgresUser: true
          postgresPassword: example
          username: example
          password: example
          database: example

